# Build Stage
FROM golang:alpine AS build-env
ADD . /
RUN cd / && go build -o telnet-server

# Final Stage
FROM alpine:latest AS final
WORKDIR /app
ENV TELNET_PORT 2323
ENV METRIC_PORT 9000
COPY -from=build-env /telnet-server /app/
ENTRYPOINT ["./telnet-server"]