apiVersion: apps/v1
kind: Deployment
metadata:
    name: telnet-server
    labels:
        apps: telnet-server
spec:
  replicas: 2
  selector:
      matchLabels:
          app: telnet-server
  strategy:
      type: RollingUpdate
      rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
  template:
    metadata:
      labels:
        app: telnet-server
    spec:
      containers:
      - image: dftd/telnet-server:v1
        imagePullPolicy: IfNotPresent
        name: telnet-server
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
          limits:
            cpu: 500m
            memory: 100Mi
          ports:
          - containerPort: 2323
            name: telnet
          - containerPort: 9000
            name: metrics
